sensor: !include_dir_merge_list config/sensors/

weather:
  - platform: darksky
    api_key: !secret darksky_api_key
    mode: daily

airvisual:
  api_key: !secret airvisual_api_key
  geographies:
    latitude: !secret latitude
    longitude: !secret longitude
