#pollens
- platform: rest
  resource: https://www.pollens.fr/risks/thea/counties/69
  name: pollens_69  
  scan_interval: 14400 #4h
  json_attributes:
    - risks
  value_template: '{{ value_json.countyName }}'
 
