#pollens
- platform: rest
  resource: https://www.pollens.fr/risks/thea/counties/69
  name: pollens_69  
  scan_interval: 14400
  json_attributes:
    - risks
  value_template: '{{ value_json.countyName }}'
  headers:
    User-Agent: Home Assistant
    Content-Type: application/json
